### ISSUE TITLE
Use of the term "Activity Request"

### ISSUE THREAD

**Issue by sreilly1** [sreilly1/Final-Year-SE-Project#18]
Should this term (in particular the table) be renamed to "applications", as it doesn't really make sense to say that a PHD student requests an activity, in the same way that a person doesn't "request" a job, but rather they apply for it.

**Comment by Fa8a6** [comment]
Why not this would make it more sense .. I'll do apply this name on my DB once I finish the work overall, hopefully this week :+1:

**Comment by sreilly1** [comment]
Too late to fix this
