### ISSUE TITLE
module_id in activity_requests table

### ISSUE THREAD

**Issue by sreilly1** [sreilly1/Final-Year-SE-Project#19]
As there is already a way to grab the module relating to a particular request using the "module" function/relationship I have defined in the Activity Model, is there really a reason for the activity request table to store the module id, as it just means storing the information in multiple places needlessly

**Comment by Fa8a6** [comment]
I have made one that does this to show: who made request + what module + activity + and if supervisor has confirmed this or not with comment on..

**Comment by sreilly1** [comment]
module_id column is no in table. Was fixed several weeks ago ago
