### ISSUE TITLE
induction activities in  "activities" table

### ISSUE THREAD

**Issue by sreilly1** [sreilly1/Final-Year-SE-Project#20]
The "module_id" field in the activities table expects a reference to the 'id' field on the modules table, however, "induction activites" don't relate to a module and thus don't have a module code. What should be done to take care of this?

**Comment by Fa8a6** [comment]
Hey Sam, that's true "Induction Activities" don't relate to a module but in our case here we named module as "Induction Activities" which include many of induction activities. However, in terms of module_id i'm working on making this nullable as well as other foreign keys. Will let you know once I deal with them :+1:

**Comment by sreilly1** [comment]
Can be inserted correctly now as per the above comment
