### ISSUE TITLE
Database change #1: 

### ISSUE THREAD

**Issue by Fa8a6** [sreilly1/Final-Year-SE-Project#23]
Table: "modules", 

Change column "module_leader" from being string to:

> ```
> $table->integer('module_leader')->unsigned()->nullable();
> $table->foreign('module_leader')->references('id')->on('users');
> ```

Reasons:
- We want to assign module leader of each module we have in records
- If a module was created and it has no module leader, **note** from the code that we made column "nullable" to cope with this issue. 
- Admin panel is already designed to cope with showing alerts if module is exists and doesn't have leader which I will show it to you guys in our next meeting.. 

Please ask if you have any questions about it.. :+1:

**Comment by sreilly1** [comment]
fixed see commit a9553cf481e9befaafab0e50f7c24ad33d12fbe3
