### ISSUE TITLE
Database change #2 

### ISSUE THREAD

**Issue by Fa8a6** [sreilly1/Final-Year-SE-Project#24]
Table: "phd_students",
- Remove **string** column "supervisor_name"

Add the following column:

> $table->integer('supervisor_id')->unsigned()->nullable();
> $table->foreign('supervisor_id')->references('id')->on('users');

Reasons:

By just inserting name we won't be able to use some existed features such as knowing more details, contacting and also something else to do with receiving confirmation acceptance (Engagement form process).

Please let me know if you have any questions :+1:

**Comment by sreilly1** [comment]
resolved, see commit 4d456b2025d419c8629be9b80471fc48602a9739
